"""add unique constraint to drawslist game_code term

Revision ID: 0ffc8371c644
Revises: bbd2ae93eee0
Create Date: 2026-05-19 16:28:32.539145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '0ffc8371c644'
down_revision: Union[str, Sequence[str], None] = 'bbd2ae93eee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_drawslist_game_term', 'drawslist', ['game_code', 'term'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_drawslist_game_term', 'drawslist', type_='unique')
    # ### end Alembic commands ###
